service: bcncgroup-image-lambda
provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1

plugins:
  - serverless-offline

functions:
  imageResizeHTTP:
    handler: handler.resize
    events:
      - http:
          path: resizeImage
          method: post
          cors: true
