service: bcncgroup-image-lambda
provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1

functions:
  imageResizeHTTP:
    handler: resizeImage.handler
    events:
      - http:
          path: resizeImage
          method: post
          cors: true
